### ISSUE TITLE
windows下使用报错

### ISSUE THREAD

**Issue by wangyiran125** [chai2010/gopherchina2018-cgo-talk#9]
make-clib-static 文件夹
在windows Cygwin64 Terminal执行make命令报错

$ make
go build -buildmode=c-archive -o number.a
# runtime/cgo
gcc_libinit_windows.c: 在函数‘x_cgo_sys_thread_create’中:
gcc_libinit_windows.c:57:12: 错误：implicit declaration of function ‘_beginthread’; did you mean ‘OpenThread’? [-Werror=implicit-function-declaration]
  thandle = _beginthread(func, 0, arg);
            ^~~~~~~~~~~~
            OpenThread
cc1：所有的警告都被当作是错误
go: failed to remove work dir: GetFileInformationByHandle D:\cygwin64new\tmp\go-build109746670\NUL: Incorrect function.
make: *** [Makefile:5：default] 错误 2

**Comment by chai2010** [comment]
之前是在 mingw（tdm-gcc）环境测试的。Cygwin64环境需要换成相应的函数名字

**Comment by wangyiran125** [comment]
我改成tdm-gcc通过了，谢谢！
